### ISSUE TITLE
Team Killing isn't detected on some mods

### ISSUE THREAD

**Issue by Xylemon** [ClaudiuHKS/AdvancedQuakeSounds#1]
It seems that some mods I host servers for (such as Scientist Hunt and OP4) that team killing isn't detected at all. Is there some way to add support in myself? Or am I missing something?

**Comment by ClaudiuHKS** [comment]
There are a lot of mods... of course...
Thank God the plug-in works on these (unknown) mods, excepting the Team Kill event.

Well, you can find **public plugin_init()** and you will see **g_bTKill = false;**.
Edit it, replacing **g_bTKill = false;** with **if (!equali(g_ModName, "SCIENTIST", strlen("SCIENTIST")) && !equali(g_ModName, "OP4", strlen("OP4"))) g_bTKill = false;**.

**Comment by Xylemon** [comment]
Ok I replaced it with:

g_bTKill = false; with if (!equali(g_ModName, "scihunt", strlen("scihunt")) && !equali(g_ModName, "gearbox", strlen("gearbox"))) g_bTKill = false;

And still nothing. Text always works (before and after code changes), but still no sounds.

**Comment by ClaudiuHKS** [comment]
Are you sure you typed the Team Kill event right in the INI file?
Are sound files OK (existing)?
What happens when you type in your console ("SPK QuakeSounds/tkill.wav") or whatever the sound is?
Either the sound file can't be played on the specified game mod or INI file has a problem.
Thanks for taking your time improving this project.

**Comment by Xylemon** [comment]
Here's what I have for Scientist Hunt (scihunt):

TEAMKILL EVENT = 1
TEAMKILL SOUNDS = scientist/stopattacking.wav
TEAMKILL HUDMSG = %s forgot which team they were on!

I have a suicide section of the ini and that plays the sound and message fine, but the team killing doesn't play a sound or message still. Even doing "SPK scientist/stopattacking.wav" in console plays the sound.

Also, I'm glad I can help make the plugin more functional. Hope this can get working.
